services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: dev-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./:/docker-entrypoint-initdb.d
  mongo-express:
    image: mongo-express
    container_name: dev-mongodb-express
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/
      ME_CONFIG_BASICAUTH: false